### ISSUE TITLE
Destroy physics entity on physics-releated script function

### ISSUE THREAD

**Issue by yangfengzzz** [galacean/runtime#1170]
When destroy physics entity on physics-releated script function, It is prevented by PhysX because it is still on update. It will throw error:
` invalid operation : PxScene::simulate: Simulation is still processing last simulate call, you should call fetchResults()! `

Demo: 
[physx-collision-detection.ts.zip](https://github.com/ant-galaxy/oasis-engine/files/9967382/physx-collision-detection.ts.zip)

**Comment by luzhuang** [comment]
fixed
