### ISSUE TITLE
gtlf loader 的结果中 modelmesh 的 indices缺失

### ISSUE THREAD

**Issue by yichen454** [galacean/runtime#1884]
**Describe the bug**
需要将导入gtlf模型进行instance渲染，目前需要通过modelmesh中信息转换到buffermesh，其中无法读取到顶点索引。 

**To Reproduce**
https://codesandbox.io/s/l45xcv?file=/index.ts
console.log(gltf);

**Screenshots**
![20231122002128](https://github.com/galacean/runtime/assets/18362833/4ca41406-ac41-427c-a0a3-ade0439878c1)

**Comment by gz65555** [comment]
上传到 gpu 后，cpu 数据就被清理掉了，如果需要保留 cpu 数据，需要加上 keepMeshData

**Comment by yichen454** [comment]
好的感谢， 我加了一个GLTFParserType.Validator设置了context里的keepMeshData得到了索引数据
还有其他API嘛

**Comment by yichen454** [comment]
找到了 load 里面可以设置

**Comment by yichen454** [comment]
![3385001823](https://github.com/galacean/runtime/assets/18362833/07da0168-75eb-414e-ba56-cd9aea106d85)
is work
