### ISSUE TITLE
Raycast 命中的 hit 数据里返回 shapeId

### ISSUE THREAD

**Issue by ch-daisy** [galacean/runtime#2003]
公益之城有一个raycast的需求，体素模型的包围盒是创建的collidershape，塞到了一个colloder里面，点击的时候希望能把命中的collidershape的id 返回，用来删除体素模型的collidershape
Collider 最好能顺便加一下 removeShapeById

**Comment by luzhuang** [comment]
我直接给你返回shape 你调用removeShape是不是也可以 @ch-daisy

**Comment by luzhuang** [comment]
https://github.com/galacean/runtime/pull/2004
